### ISSUE TITLE
Avoid code duplication with DDatElectron

### ISSUE THREAD

**Issue by eight04** [dd-center/DDatHome-nodejs#3]
Some code is duplicated with https://github.com/dd-center/DDatElectron/blob/3d76a744219360debe35cdb6772d9f8d79b4b4be/src/ws.js

I think we can make DDatHome-nodejs more modular, so DDatElectron can use it. Imagine something like:

```js
const ddCore = require("DDatHome-nodejs");
ddCore.startDD({
  interval: await getInterval()
  runtime: `DDatHomeCore ${ddCore.version}, DDatElectron ${...}, Electron ${...}`,
  ... // and other configurable options
  onlog(logLevel, message) {
    // redirect log to the UI
  }
});
```
It also helps #1 by making the current code more modular,

**Comment by simon300000** [comment]
I am actually not planing to publish this as a module, since this is a private project,
But maybe later on I can standardize this "Over WebSocket" protocol which then I can somehow publish it

But this is a good idea, the time of writing of this code is actually in hurry, now I have more time to deal with problem like this.

**Comment by eight04** [comment]
You can still keep it private if you don't want to publish it to npmjs.com. `npm` can install dependencies from Github: `npm install <user>/<repository>`. For this project, the command is `npm install dd-center/DDatHome-nodejs`

**Comment by simon300000** [comment]
ahaha I know that

**Comment by simon300000** [comment]
currently I use a class extends EventEmitter as a API, next step I will embed it into dd-monitor
